src/Entity/Game.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Date;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 */
class Game
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $short;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $crossLimit;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $penaltyLimit;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $playerLimit;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $crossNorm;

    /**
     * @ORM\Column(type="smallint")
     */
    private $type;

    /**
     * @ORM\Column(type="boolean",nullable=true)
     */
    private $moderated;

    /**
     * @ORM\Column(type="smallint")
     */
    private $stepDay;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $end;

    /**
     * @ORM\Column(type="boolean")
     */
    private $canChange;

    /**
     * @ORM\Column(type="boolean")
     */
    private $canJoin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $needPhoto;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="myGames")
     */
    private $organizer;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Player", mappedBy="game", cascade={"remove"})
     */
    private $players;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\GameStep", mappedBy="game", cascade={"remove"})
     * @ORM\OrderBy({"date" = "ASC"})
     */
    private $steps;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="game",cascade={"all"})
     * @ORM\OrderBy({"created_at"="DESC"})
     */
    private $comments;

    public function __construct()
    {
        $this->setStart((new \DateTime())->add(\DateInterval::createFromDateString('2 days')));
        $this->setType(1);
        $this->setStepDay(7);
        $this->setCrossLimit(100000);
        $this->setCrossNorm(200);
        $this->setPenaltyLimit(600);
        $this->setPlayerLimit(20);
        $this->setNeedPhoto(true);
        $this->setCanChange(true);
        $this->setCanJoin(true);
        $this->players = new ArrayCollection();
        $this->steps = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function active()
    {
        return $this->getModerated() && !$this->getEnd() || new \DateTime() < $this->getEnd();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * @return \DateTime|null
     */
    public function lastStepDate()
    {
        if ($this->steps->count() > 0) {
            return $this->steps->last()->getDate();
        }
        return $this->getStart();
    }

    /**
     * @param GameStep $gameStep
     * @return GameStep | null
     */
    public function beforeStep(GameStep $gameStep)
    {
        $index = $this->steps->indexOf($gameStep);
        if ($index && $index > 0) {
            return $this->steps->get($index - 1);
        }
        return null;
    }

    /**
     * @return GameStep|null
     */
    public function lastStep()
    {
        if ($this->steps->count() > 0) {
            return $this->steps->last();
        }
        return null;
    }

    public function setStart(\DateTime $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * @param \DateTime|null $end
     * @return Game
     */
    public function setEnd($end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getCanChange(): ?bool
    {
        return $this->canChange;
    }

    public function setCanChange(bool $canChange): self
    {
        $this->canChange = $canChange;

        return $this;
    }

    public function getCanJoin(): ?bool
    {
        return $this->canJoin;
    }

    public function setCanJoin(bool $canJoin): self
    {
        $this->canJoin = $canJoin;

        return $this;
    }

    public function getNeedPhoto(): ?bool
    {
        return $this->needPhoto;
    }

    public function setNeedPhoto(bool $needPhoto): self
    {
        $this->needPhoto = $needPhoto;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCrossLimit()
    {
        return $this->crossLimit;
    }

    /**
     * @param mixed $crossLimit
     */
    public function setCrossLimit($crossLimit): void
    {
        $this->crossLimit = $crossLimit;
    }

    /**
     * @return integer
     */
    public function getStepDay()
    {
        return $this->stepDay;
    }

    /**
     * @param mixed $stepDay
     */
    public function setStepDay($stepDay): void
    {
        $this->stepDay = $stepDay;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getCrossNorm()
    {
        return $this->crossNorm;
    }

    /**
     * @param mixed $crossNorm
     */
    public function setCrossNorm($crossNorm): void
    {
        $this->crossNorm = $crossNorm;
    }


    /**
     * @return mixed
     */
    public function getPenaltyLimit()
    {
        return $this->penaltyLimit;
    }

    /**
     * @param mixed $penaltyLimit
     */
    public function setPenaltyLimit($penaltyLimit): void
    {
        $this->penaltyLimit = $penaltyLimit;
    }

    /**
     * @return mixed
     */
    public function getPlayerLimit()
    {
        return $this->playerLimit;
    }

    /**
     * @param mixed $playerLimit
     */
    public function setPlayerLimit($playerLimit): void
    {
        $this->playerLimit = $playerLimit;
    }

    /**
     * @return mixed
     */
    public function getOrganizer()
    {
        return $this->organizer;
    }

    /**
     * @param mixed $organizer
     */
    public function setOrganizer($organizer): void
    {
        $this->organizer = $organizer;
    }

    /**
     * @return ArrayCollection
     */
    public function getPlayers()
    {
        return $this->players;
    }

    /**
     * @return ArrayCollection
     */
    public function getActivePlayers()
    {
        return $this->getPlayers()->filter(function (Player $player) {
            return !$player->getGameOver();
        });
    }

    /**
     * @param GameStep $player
     * @return mixed
     */
    public function addPlayer($player)
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
        }
        return $this;
    }

    /**
     * @param GameStep $player
     * @return mixed
     */
    public function removePlayer($player)
    {
        if ($this->players->contains($player)) {
            return $this->players->removeElement($player);
        }
        return $this;
    }

    /**
     * @return mixed
     */
    public function getModerated()
    {
        return $this->moderated;
    }

    /**
     * @param mixed $moderated
     */
    public function setModerated($moderated): void
    {
        $this->moderated = $moderated;
    }

    /**
     * @param User $user
     * @return bool
     */
    public function inGame(User $user)
    {
        return !is_null($this->getPlayerForUser($user));
    }

    /**
     * @param User $user
     * @return Player|null
     */
    public function getPlayerForUser(User $user)
    {
        $res = $this->players->filter(function (Player $player) use ($user) {
            return $player->getUser() === $user && !$player->getGameOver();
        });
        if ($res->count() > 0) {
            return $res->first();
        }
        return null;
    }

    /**
     * @return ArrayCollection
     */
    public function getSteps()
    {
        return $this->steps;
    }

    /**
     * @return mixed
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @return mixed
     */
    public function getShort()
    {
        return $this->short;
    }

    /**
     * @param mixed $short
     */
    public function setShort($short): void
    {
        $this->short = $short;
    }

    public function isActual()
    {
        return !$this->getEnd() || $this->getEnd() >= (new \DateTime());
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 */
class Page
{
    const NEWS = 1;
    const PAGE = 0;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="smallint")
     */
    private $type = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }
}

src/Entity/Reward.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RewardRepository")
 */
class Reward
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Player", inversedBy="rewards")
     */
    private $player;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\RewardType")
     */
    private $reward_type;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * @param mixed $player
     */
    public function setPlayer($player): void
    {
        $this->player = $player;
    }

    /**
     * @return mixed
     */
    public function getRewardType()
    {
        return $this->reward_type;
    }

    /**
     * @param mixed $reward_type
     */
    public function setRewardType($reward_type): void
    {
        $this->reward_type = $reward_type;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    private $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('short')
            ->add('description', null, [
                'attr' => [
                    'data-emo' => true
                ]
            ])
            ->add('start', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datepicker'
                ]
            ])
            ->add('end', DateType::class, [
                'required' => false,
                'label' => 'game_end',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datepicker'
                ]
            ])
            ->add('crossLimit')
            ->add('penaltyLimit')
            ->add('playerLimit')
            ->add('crossNorm')
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Норма в неделю' => 1,
                    'Кто быстрее' => 2,
                    'Кто больше' => 3,
                ]
            ])
            ->add('stepDay', ChoiceType::class, [
                'choices' => [
                    'Понедельник' => 1,
                    'Вторник' => 2,
                    'Среда' => 3,
                    'Четверг' => 4,
                    'Пятница' => 5,
                    'Суббота' => 6,
                    'Воскресенье' => 7,
                ]
            ])
            ->add('canChange')
            ->add('canJoin')
            ->add('needPhoto');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

templates/game/archive.html.twig
{% extends 'base.html.twig' %}

{% block title %}Архив игр{% endblock %}

{% block content %}
    <h2 class=" text-center mb-3">Завершенные игры</h2>
    <div class="row">
        <div class="col-12">
            {% include 'game/table.html.twig' %}
        </div>
    </div>
{% endblock %}

templates/game/comments.html.twig
{% extends '/game/layout.html.twig' %}

{% block info %}
    <style>
        .content {
            display: flex;
            flex-direction: column;
        }

        footer {
            display: none !important;
        }
    </style>
    <div class="messages game-comments d-flex flex-column flex-grow-1">
        {% include 'flash.html.twig' %}
        <div class="message-box flex-grow-1 rounded d-flex flex-column">
            <div class="list-unstyled flex-grow-1 position-relative" id="message-table" data-game="{{ game.id }}">
                <div class="bg-message"></div>
            </div>
        </div>
        {% if app.user %}
            {% set user = app.user %}
            <div class="message-input mt-2">
                <form method="post" action="{{ path('app_game_addcomment',{id:game.id}) }}">
                    <div class="d-flex flex-row">
                        <div class="input-group">
                            <textarea minlength="1" class="form-control" name="comment"
                                      rows="1"
                                      data-emo
                                      placeholder="Начните печатать сообщение..." type="text"></textarea>
                            <span class="input-group-append">
                            <button type="submit" title="Отправить" class="btn btn-primary">
                                <i class="fa fa-paper-plane"></i>
                                <span class="d-none d-md-inline">Отправить</span>
                            </button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/messages.js') }}"></script>
{% endblock %}

templates/game/comments_table.html.twig
{% for comment in game.comments | reverse %}
    {% set itsMine = comment.user == app.user %}
    {% if lastUser is not null and comment.user != lastUser %}
        {% set isTo = not isTo %}
    {% endif %}
    {% set lastUser = comment.user %}
    <div class="message game-comment {{ isTo?'to':'from' }} {{ comment.user == game.organizer?'organizer':'' }}"
         style="min-height: 50px">
        <div class="message-content">
            <div class="avatar" style="overflow: hidden;">
                {% include 'image.html.twig' with {image:comment.user.image} %}
            </div>
            <div>
                <a href="{{ path('app_profile_show',{id:comment.user.id}) }}"> {{ comment.user.username }}</a>:
                <span class="message-text emo">{{ comment.comment | nl2br }}</span>
            </div>
            <div class="small  {{ isTo?'':'text-right' }}">
                                <span class="text-light">
                                        {{ comment.createdAt | date ('d.m.Y H:i:s') }}
                                    </span>
                {% if itsMine %}
                    <button class="btn btn-link p-0" title="Редактировать сообщение"
                            onclick="editGameComment(this,{{ comment.id }}, {{ comment.game.id }})">
                        <i class="fa fa-pencil"></i>
                    </button>
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}

templates/game/edit.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">{{ game.id?'Сохранить':'Создать' }}</button>
            <a class="btn btn-secondary" href="{{ path('app_profile_games',{id:app.user.id}) }}">Отмена</a>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/game/gallery.html.twig
{% extends '/game/layout.html.twig' %}

{% block info %}
    <div class="row">
        {% for project in projects %}
            {% if project.image %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3 position-relative d-flex flex-column">
                    <div class="border p-2">
                        <a class="h-font" href="{{ path('app_project_show',{id:project.id}) }}">
                            {{ project.name }}
                        </a>
                        <div class="square mt-2">
                            {% include 'image.html.twig' with {image : project.image, preview:true} %}
                            <a class="h-font sign no-decor " href="{{ path('app_profile_show',{id:project.user.id}) }}">{{ project.user.username }}</a>
                        </div>
                        <span class="text-light small">{{ project.end | date('d.m.Y') }}</span>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

{% block title %}
    Галерея вышитых работ в игре {{ game.name }}
{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Игры{% endblock %}

{% block content %}
    {% if is_granted('ROLE_SUPER_ADMIN') %}
        <a class="btn btn-secondary" href="{{ path('app_game_moderate') }}">Игры на модерации</a>
    {% endif %}
    <h2 class=" text-center mb-3">Текущие игры</h2>
    <div class="row">
        <div class="col-12">
            {% include 'game/table.html.twig' %}
        </div>
    </div>
    <a href="{{ path('app_game_archive') }}" class="btn btn-primary"><i class="fa fa-archive"></i> Архив игр</a>
{% endblock %}

templates/game/join.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h3>Выберите проект для игры</h3>
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Присоединиться</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/game/layout.html.twig
{% extends 'base.html.twig' %}

{% set in_game = app.user and inGame(app.user,game) %}
{% set can_join = canJoin(app.user,game) %}

{% block content %}
    <h2 class="text-center mb-3">Игра № {{ game.id }} {{ game.name }}</h2>
    <div class="row">
        <div class="col-12 mb-3">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link {{ app.request.pathInfo==path('app_game_show',{id:game.id})?'active':'' }}"
                       href="{{ path('app_game_show',{id:game.id}) }}">
                        <i class="fa fa-check"></i>
                        Игра</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ app.request.pathInfo==path('app_game_steps',{id:game.id})?'active':'' }}"
                       href="{{ path('app_game_steps',{id:game.id}) }}">
                        <i class="fa fa-calendar"></i>
                        Ходы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ app.request.pathInfo==path('app_game_comments',{id:game.id})?'active':'' }}"
                       href="{{ path('app_game_comments',{id:game.id}) }}">
                        <i class="fa fa-comments"></i>
                        Комментарии</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ app.request.pathInfo==path('app_game_gallery',{id:game.id})?'active':'' }}"
                       href="{{ path('app_game_gallery',{id:game.id}) }}">
                        <i class="fa fa-image"></i>
                        Галерея</a>
                </li>
            </ul>
        </div>
    </div>

    {% block info %}

    {% endblock %}
{% endblock %}

templates/game/moderate.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <h2 class="text-center  mb-3">Игры для модерации</h2>
    <div class="row">
        <div class="col-12">
            {% include '/game/table.html.twig' with {can_moderate_game:true} %}
        </div>
    </div>
{% endblock %}

templates/game/reward.html.twig
{% if player.rewards | length > 0 %}
    <ul class="list-group mb-3">
        {% for reward in player.rewards %}
            <li class="list-group-item">
                {{ reward.rewardType.name }}
                {{ reward.createdAt | date('d.m.Y H:i') }}
                {% include 'reward.html.twig' %}
                <a class="btn btn-primary btn-sm" href="{{ path('app_game_cancelreward',{reward_id:reward.id}) }}">Отменить</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}
<form method="post" action="{{ path('app_game_reward',{player_id:player.id}) }}">
    <div class="form-group">
        <select name="type" class="form-control">
            {% for type in types %}
                <option value="{{ type.id }}" data-img="{{ type.image }}">
                    {{ type.name }}
                </option>
            {% endfor %}
        </select>
    </div>
    <button class="btn btn-primary">Наградить</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
</form>

templates/game/show.html.twig
{% extends '/game/layout.html.twig' %}

{% block info %}
    <div class="row">
        <div class="col-12 mb-3">
            <div>Ведущий: {% include 'profile.html.twig' with {profile:game.organizer} %}</div>
            <div>Участники: {% for player in game.activePlayers %}
                    {% include 'profile.html.twig' with{profile:player.user} %}{% if not loop.last %}; {% endif %}
                {% endfor %}
            </div>
            <div>{{ 'Start'|trans }}: {{ game.start | date ('d.m.Y') }}</div>
            <div class="border rounded p-1 emo">{{ 'Description'|trans }}: {{ game.description | nl2br }}</div>
            <div>{{ 'Cross limit'|trans }}: {{ game.crossLimit }}</div>
            <div>{{ 'Penalty limit'|trans }}: {{ game.penaltyLimit }}</div>
            <div>{{ 'Player limit'|trans }}: {{ game.playerLimit }}</div>
            <div>{{ 'Cross norm'|trans }}: {{ game.crossNorm }}</div>
            <div>{{ 'Step day'|trans }}: {{ game.stepDay | stepDay }}</div>
            <div>{{ game.canChange?'Можно':'Нельзя' }} менять проект</div>
            <div>{{ game.canJoin?'Можно':'Нельзя' }} присоединиться после старта</div>
            <div>Фотоотчет {{ game.needPhoto?'обязателен':'не обязателен' }}</div>
            <hr/>
            {% if can_join %}
                <a href="{{ path('app_game_join', {'id': game.id}) }}" class="btn btn-primary">
                    <i class="fa fa-check"></i>
                    Присоединиться к игре
                </a>
            {% endif %}
            {% if in_game %}
                {% if  game.canChange %}
                    <a href="{{ path('app_game_projectchange', {'id': game.id}) }}" class="btn btn-secondary">
                        <i class="fa fa-file"></i>
                        Сменить проект
                    </a>
                {% endif %}
                <button onclick="leave('{{ path('app_game_leave', {'id': game.id}) }}')" class="btn btn-primary">
                    <i class="fa fa-sign-out"></i>
                    Покинуть игру
                </button>
            {% endif %}
        </div>
    </div>
{% endblock %}

    {% block javascripts %}
        <script>
            function leave(url) {
                if (window.confirm('Вы действительно хотите покинуть игру? Прогресс будет удален.')) {
                    location.href = url;
                }
            }
        </script>
    {% endblock %}

templates/game/status.html.twig
{% if game.moderated == null %}
    {% set class = 'warning' %}
{% elseif game.moderated == true%}
    {% set class = 'success' %}
{% elseif game.moderated == false %}
    {% set class = 'danger' %}
{% endif %}

<div class="badge badge-{{ class }}">
    {{ game | gameStatus }}
</div>

templates/game/table.html.twig
{% set can_edit_game = can_edit_game | default(false) %}
{% set show_status = show_status | default(false) %}
{% set can_moderate_game = can_moderate_game | default(false) %}
{% set dynamic_limit = dynamic_limit | default(false) %}
<div class="table-responsive">
    <table class="table table-sm table-bordered">
        <thead>
        <tr>
            <th>{{ 'Name'|trans }}</th>
            <th>{{ 'Description'|trans }}</th>
            <th>{{ 'Type'|trans }}</th>
            <th>{{ 'Start'|trans }}</th>
            <th>{{ 'Players'|trans }}</th>
            <th>{{ 'Cross norm'|trans }}</th>
            {% if show_status %}
                <th>Статус</th>
            {% endif %}
            {% if can_edit_game %}
                <th></th>
            {% endif %}
            {% if can_moderate_game %}
                <th></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <td><a href="{{ path('app_game_show', {'id': game.id}) }}">{{ game.name }}</a></td>
                <td class="emo">{% if game.short is not null and game.short | length > 0 %}{{ game.short }}{% else %}{{ game.description | slice(0,100) }}{{ game.description | length > 100 ? '...':'' }}{% endif %}</td>
                <td>{{ game.type | gameType }}</td>
                <td>{{ game.start | date ('d.m.Y') }}</td>
                <td>{{ game.activePlayers | length }}{% if game.playerLimit %} из {{ game.playerLimit }}{% endif %}</td>
                <td>
                    {% if dynamic_limit and app.user %}
                        {{ mustCross(game,app.user) }} из {{ game.crossNorm }}
                    {% else %}
                        {{ game.crossNorm }}
                    {% endif %}
                </td>
                {% if show_status != false %}
                    <td>{% include '/game/status.html.twig' %}</td>
                {% endif %}
                {% if can_edit_game %}
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a class="btn btn-secondary btn-sm" title="Редактировать"
                               href="{{ path('app_game_edit', {'id': game.id}) }}">
                                <i class="fa fa-pencil"></i>
                            </a>
                            {% if game.moderated %}
                                <a class="btn  btn-primary btn-sm" title="Удалить"
                                   href="{{ path('app_game_remove', {'id': game.id}) }}">
                                    <i class="fa fa-trash"></i>
                                </a>
                            {% endif %}
                        </div>
                    </td>
                {% endif %}
                {% if can_moderate_game %}
                    <td>
                        <a class="btn btn-sm btn-primary"
                           href="{{ path('app_game_approve', {'id': game.id,approve:true}) }}">Одобрить</a>
                        <a class="btn btn-sm btn-secondary"
                           href="{{ path('app_game_approve', {'id': game.id}) }}">Отклонить</a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>